name: verigraph_env
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge

dependencies:
  # --- Core Python ---
  - python=3.10
  - pip>=23.0

  # --- Core Libraries ---
  - pytorch>=2.2.0
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1  # match CUDA version on your cluster

  # --- Standard Packages ---
  - pip:
      - transformers>=4.39.0
      - datasets>=2.19.0
      - accelerate>=0.29.0
      - bitsandbytes>=0.43.0

      # --- Graph Reasoning ---
      - dgl-cu121>=1.1.3  # use 'dgl' instead if CUDA not available

      # --- Fine-tuning / Training ---
      - peft>=0.8.2
      - scikit-learn>=1.4.0
      - numpy>=1.26.0
      - scipy>=1.12.0
      - pandas>=2.2.0

      # --- Visualization / Evaluation ---
      - matplotlib>=3.8.0
      - networkx>=3.2.1
      - seaborn>=0.13.2

      # --- Logging / Utils ---
      - tqdm>=4.66.0
      - pyyaml>=6.0
      - jsonlines>=4.0.0

      # --- Optional Jupyter Support ---
      - notebook>=7.0.6
      - jupyter>=1.0.0
